# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'My pc'
      demands:
        - Agent.Name -equals R
    steps:

    - script: |
        mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f myapp/pom.xml > version.txt
        set /p PROJECT_VERSION=<version.txt
        echo Project Version is %PROJECT_VERSION%
        echo ##vso[task.setvariable variable=PROJECT_VERSION]%PROJECT_VERSION%
      displayName: get_version
      
    - script: |
        echo "Using project version: $(PROJECT_VERSION)"
      displayName: use_version
