# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'My pc'
      demands:
        - Agent.Name -equals R
    steps:
    - script: |
        echo "Building Docker image..."
        docker build ./myapp -t $(IMAGE_NAME)
      displayName: Docker Build
    
    - script: |
        cp ./myapp/pom.xml ./myapp/backup_pom.xml
        docker create --name temp $(IMAGE_NAME)
        docker cp temp:/app/pom.xml ./myapp/pom.xml
        docker rm temp
      displayName: backup_pom

    - script: |
        for /f "delims=" %%v in ('mvn help:evaluate -Dexpression=project.version -q -DforceStdout') do set version=%%v
        echo "Detected JAR version: %version%
        echo "##vso[task.setvariable variable=JAR_VERSION]%version%"
      displayName: get_version

    - script: |
        docker tag $(IMAGE_NAME) $(DOCKER_HUB_USERNAME)/$(REPO_NAME):$(JAR_VERSION)
        docker tag $(IMAGE_NAME) $(DOCKER_HUB_USERNAME)/$(REPO_NAME):latest
      displayName:  tag_image