# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'My pc'
      demands:
        - Agent.Name -equals R
    steps:
    - script: |
        echo "Building Docker image..."
        docker build ./myapp -t $(IMAGE_NAME)
      displayName: Docker Build
    
    - script: |
        cp ./myapp/pom.xml ./myapp/backup_pom.xml
        docker create --name temp $(IMAGE_NAME)
        docker cp temp:/app/pom.xml ./myapp/pom.xml
        docker rm temp
      displayName: backup_pom
