name: Build and Deploy Java app

on:
  push:
    branches:
      - workflow-update

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      IMAGE_NAME: hello-world
      REPO_NAME: hello-world

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build ./myapp -t ${{ env.IMAGE_NAME }}

      - name: Backup current pom.xml and create container for extracting new version of pom.xml 
        run: |
          cp ./myapp/pom.xml ./myapp/backup_pom.xml
          docker create --name temp ${{ env.IMAGE_NAME }}
          docker cp temp:/app/pom.xml ./myapp/pom.xml
          docker rm temp
      
      - name: Get jar version from the extracted pom file
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f myapp/pom.xml)
          echo "JAR_VERSION=$version" >> $GITHUB_ENV

      - name: Tag docker image 
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
          docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Commit new jar version
        id: commit_pom
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add myapp/pom.xml
          git commit -m "new jar version"
          git push origin workflow-update

      - name: Push Docker image to Docker Hub
        id: push_img
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
          
      - name: Pull Docker image from Docker Hub
        id: pull_img
        run: |
          docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
          exit 1

      - name: Run Docker Image
        id: check_img
        run: |
          docker run --rm ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
      
      - name: Push image as latest
        if: steps.check_img.outcome == 'success'
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest
          
      - name: Remove docker image if failed to run from Docker Hub
        if: failure()
        run: |
          curl -s -X DELETE \
            -u ${{ env.DOCKER_HUB_USERNAME }}:${{ env.DOCKER_HUB_ACCESS_TOKEN }} \
            "https://hub.docker.com/v2/repositories/${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}/tags/$JAR_VERSION"

