name: Build and Deploy Java app

on:
  push:
    branches:
      - workflow-update

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      IMAGE_NAME: hello-world
      REPO_NAME: hello-world

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build ./myapp -t ${{ env.IMAGE_NAME }}

      - name: Get jar version from the extracted pom file
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f myapp/pom.xml)
          echo "JAR_VERSION=$version" >> $GITHUB_ENV

      - name: Tag docker image 
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
          docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Commit new jar version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add myapp/pom.xml
          git commit -m "new jar version"
          git push origin workflow-update

      - name: Remove local Docker image
        run: |
          docker rmi ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:$JAR_VERSION
          docker rmi ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Run Docker Image
        run: |
          docker run --rm ${{ env.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest

