name: Build and Deploy Java app
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Increase the Patch part of the jar version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f myapp/pom.xml)
          echo "Current version: ${version}"
          new_version=$(echo ${version} | awk -F'.' '{print $1"."$2"."$3+1}')
          echo "New version: ${new_version}"
          mvn versions:set -DnewVersion=${new_version} -f myapp/pom.xml
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
          
      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add myapp/pom.xml
          git commit -m "new jar version"
          git push origin main
          
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./myapp
          file: ./myapp/Dockerfile
          push: false
          tags: justme2024/hello-world:${{ env.NEW_VERSION }}
          build-args: VER=${{ env.NEW_VERSION }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Push Docker Image to Docker Hub
        run: |
          docker push justme2024/hello-world:${{ env.NEW_VERSION }}
          
      - name: Remove local Docker image (to force pull)
        run: |
          docker rmi justme2024/hello-world:${{ env.NEW_VERSION }} || echo "Image not found locally"
          
      - name: Run Docker Image (non-root)
        run: |
          docker run --rm --user 1000:1000 justme2024/hello-world:${{ env.NEW_VERSION }}
