name: Build and Deploy Java app

on:
  push:
    branches:
      - workflow-update

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Increase the Patch part of the jar version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f myapp/pom.xml)
          echo "Current version: ${version}"
          new_version=$(echo ${version} | awk -F'.' '{print $1"."$2"."$3+1}')
          echo "New version: ${new_version}"
          mvn versions:set -DnewVersion=${new_version} -f myapp/pom.xml
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
          
      - name: Commit new jar version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add myapp/pom.xml
          git commit -m "new jar version"
          git push origin workflow-update
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}     
      
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./myapp
          file: ./myapp/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/hello-world:${{ env.NEW_VERSION }}
     
      - name: Remove local Docker image
        run: |
          docker rmi ${{ env.DOCKER_HUB_USERNAME }}/hello-world:${{ env.NEW_VERSION }} || echo "Image not found locally"
          
      - name: Run Docker Image
        run: |
          docker run --rm ${{ env.DOCKER_HUB_USERNAME }}/hello-world:${{ env.NEW_VERSION }}

